name: Problema enfrentado
description: Um problema que se apresenta como impedimento ou desvantagem para continuarmos desempenhando um bom trabalho.
title: "[Problema]: "

body:
  - type: markdown
    attributes:
      value: |
        Lembre sempre de analisar os problemas existente e além de ser assertivo trazer propostas de soluções.
  - type: textarea
    id: problema-a-enfrentar
    attributes:
      label: Problema
      description: |
        Faça uma descrição curta de qual problema a enfrentar.
      placeholder: Descreva o problema e como ele nos impede de performar melhor.
  - type: textarea
    id: solucao-abordada
    attributes:
      label: Solução
      description: |
        Descreva quais opções possíveis para resolver o problema.
      placeholder: Descreva a proposta de alteração, remoção ou adição.
    validations:
      required: true
  - type: textarea
    id: vantagens-da-solução
    attributes:
      label: Vantagens
      description: |
        Quais benefícios podem ser aproveitados dessa solução?
      placeholder: Descreva as vantagens 
    validations:
      required: true
  - type: textarea
    id: desvantagens-do-problema
    attributes:
      label: Desvantagens
      description: |
        Como manter o problema pode impactar nos nossos esforços?
      placeholder: Descreva as desvantagens de continuar enfrentando esse problema.

  - type: checkboxes
    id: terms
    attributes:
      label: Termos
      description: |
        Por favor, marque a caixa abaixo para indicar que você leu e concorda com os termos da comunidade.
      options:
        - label: Eu li e concordo com os termos de contribuicao comunidade no link abaixo ⬇️.
          required: true
